### ISSUE TITLE
Add retrying?

### ISSUE THREAD

**Issue by maelle** [ropensci/worrms#28] opened 2022-01-17 13:59 UTC
I just got this error 

```r
 Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) :
  Error in the HTTP2 framing layer
```

for a query that has worked previously and worked again after that. Would using RETRY instead of GET help with this?

**Comment by bart-v** [comment] 2023-06-21 09:44
Feel free to make a PR

**Comment by bart-v** [comment] 2023-06-21 09:45
Duplicate of https://github.com/ropensci/worrms/issues/27
Closing

**Closed as completed by bart-v** 2023-06-21 09:45 UTC
Labels: enhancement
